/* -*- Mode: C; c-basic-offset: 4; -*-
 *
 * EMEROBOT, JAVASCRIPT ERROR CODES
 *
 * ### Programmed by kashey@protonmail.com,
 * ### source code published under terms of GPLv3 license.
 *
 */

#ifndef EMEROBOTEC_H_INCLUDED
#define EMEROBOTEC_H_INCLUDED


#define EMEROBOT_ERR_INVALID_AMOUNT                  6003
#define EMEROBOT_ERR_ADDRESS_DOES_NOT_REFER_TO_KEY   6003
#define EMEROBOT_ERR_PRIVATE_KEY_NOT_AVAILABLE       6004
#define EMEROBOT_ERR_TRANSACTION_CREATION_FAILED     6004
#define EMEROBOT_ERR_TRANSACTION_COMMIT_FAILED       6004
#define EMEROBOT_ERR_ERROR_REFRESHING_KEYPOOL        6004
#define EMEROBOT_ERR_INVALID_EMERCOIN_ADDRESS        6005
#define EMEROBOT_ERR_SIGN_FAILED                     6005
#define EMEROBOT_ERR_MALFORMED_BASE64_ENCODING       6005
#define EMEROBOT_ERR_INVALID_TRANSACTION_ID          6005
#define EMEROBOT_ERR_NON_WALLET_TRANSACTION_ID       6005
#define EMEROBOT_ERR_BLOCK_NOT_FOUND                 6005
#define EMEROBOT_ERR_ACCOUNT_HAS_INSUFFICIENT_FUNDS  6006
#define EMEROBOT_ERR_OUT_OF_MEMORY                   6007
#define EMEROBOT_ERR_DUPLICATED_ADDRESS              6008
#define EMEROBOT_ERR_IS_NOT_CONNECTED                6009
#define EMEROBOT_ERR_BLOCKS_DOWNLOAD_INCOMPLETE      6010
#define EMEROBOT_ERR_INVALID_ACCOUNT_NAME            6011
#define EMEROBOT_ERR_KEYPOOL_RAN_OUT                 6012
#define EMEROBOT_ERR_WALLET_IS_LOCKED                6013
#define EMEROBOT_ERR_INCORRECT_WALLET_PASSPHRASE     6014
#define EMEROBOT_ERR_WALLET_IS_UNENCRYPTED           6015
#define EMEROBOT_ERR_FAILED_TO_ENCRYPT_WALLET        6016
#define EMEROBOT_ERR_DATABASE_ERROR                  6020
#define EMEROBOT_ERR_BLOCK_DECODE_FAILED             6021
#define EMEROBOT_ERR_UNABLE_TO_SIGN_BLOCK            6100
#define EMEROBOT_ERR_SEND_AMOUNT_TOO_SMALL           6101


#endif

